@startuml
class de.htwg.co2footprint_tracker.views.data.DataFragment {
~ FragmentDataBinding binding
~ DatabaseHelper databaseHelper
~ List<Co2Equivalent> co2Equivalents
~ ViewGroup container
+ {static} DataFragment getInstance()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void bindDataAccordingToToggleStatus()
- DataRecyclerViewAdapter getDataRecyclerViewAdapter(ViewGroup)
+ void onViewCreated(View,Bundle)
- void bindTodayData()
- void bindTotalData()
}
class de.htwg.co2footprint_tracker.model.Package {
- String name
- String version
- String packageName
- int packageUid
- boolean duplicateUids
- long receivedBytesWifi
- long receivedBytesMobile
- long receivedBytesTotal
- long transmittedBytesWifi
- long transmittedBytesMobile
- long transmittedBytesTotal
- long receivedPacketsWifi
- long receivedPacketsMobile
- long receivedPacketsTotal
- long transmittedPacketsWifi
- long transmittedPacketsMobile
- long transmittedPacketsTotal
- long timestamp
- double energyConsumption
- ConnectionType connectionType
+ {static} Creator<Package> CREATOR
+ String getName()
+ void setName(String)
+ String getVersion()
+ void setVersion(String)
+ String getPackageName()
+ void setPackageName(String)
+ int getPackageUid()
+ void setPackageUid(int)
+ boolean getDuplicateUids()
+ void setDuplicateUids(boolean)
+ long getReceivedBytesWifi()
+ void setReceivedBytesWifi(long)
+ long getReceivedBytesMobile()
+ void setReceivedBytesMobile(long)
+ long getReceivedBytesTotal()
+ void setReceivedBytesTotal(long)
+ long getTransmittedBytesWifi()
+ void setTransmittedBytesWifi(long)
+ long getTransmittedBytesMobile()
+ void setTransmittedBytesMobile(long)
+ long getTransmittedBytesTotal()
+ void setTransmittedBytesTotal(long)
+ long getReceivedPacketsWifi()
+ void setReceivedPacketsWifi(long)
+ long getReceivedPacketsMobile()
+ void setReceivedPacketsMobile(long)
+ long getReceivedPacketsTotal()
+ void setReceivedPacketsTotal(long)
+ long getTransmittedPacketsWifi()
+ void setTransmittedPacketsWifi(long)
+ long getTransmittedPacketsMobile()
+ void setTransmittedPacketsMobile(long)
+ long getTransmittedPacketsTotal()
+ void setTransmittedPacketsTotal(long)
+ long getTimestamp()
+ void setTimestamp(long)
+ double getEnergyConsumption()
+ void setEnergyConsumption(double)
+ ConnectionType getConnectionType()
+ void setConnectionType(ConnectionType)
+ int compareTo(Object)
+ int describeContents()
+ void writeToParcel(Parcel,int)
}
class de.htwg.co2footprint_tracker.views.tips.ExpandableListViewAdapter {
- Context context
- List<String> listDataGroup
- HashMap<String,List<String>> listDataChild
+ Object getChild(int,int)
+ long getChildId(int,int)
+ View getChildView(int,int,boolean,View,ViewGroup)
+ int getChildrenCount(int)
+ Object getGroup(int)
+ int getGroupCount()
+ long getGroupId(int)
+ View getGroupView(int,boolean,View,ViewGroup)
+ boolean hasStableIds()
+ boolean isChildSelectable(int,int)
}
class de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter {
- List<Co2Equivalent> co2Equivalents
- LayoutInflater mInflater
- ItemClickListener mClickListener
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ Co2Equivalent getItem(int)
+ void setClickListener(ItemClickListener)
}
interface de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter.ItemClickListener {
~ void onItemClick(View,int)
}
class de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter.ViewHolder {
- Co2EquivalenceCardBinding binding
~ CardView view
+ void bind(Co2Equivalent)
+ void onClick(View)
}
class de.htwg.co2footprint_tracker.model.MainCardModel {
- long totalReceivedBytes
- double totalEnergyConsumption
+ String getReceivedBytes()
+ String getTotalEnergyConsumption()
}
class de.htwg.co2footprint_tracker.helpers.LocationHelper {
~ FusedLocationProviderClient fusedLocationProviderClient
- MainActivity activity
- {static} LocationHelper locationHelper
+ {static} LocationHelper getInstance()
+ void updateCurrentAdminArea()
+ void onRequestPermissionsResult(int,String[],int[])
}
class de.htwg.co2footprint_tracker.model.TipItem {
- String title
- String description
+ String getDescription()
+ void setDescription(String)
+ String getTitle()
+ void setTitle(String)
}
class de.htwg.co2footprint_tracker.utils.DataUtils {
+ {static} List<Consumer> CursorToConsumerList(Cursor,Context)
}
class de.htwg.co2footprint_tracker.utils.UnitUtils {
+ {static} String humanReadableByteCountSI(long)
+ {static} long getMidnightTimestamp()
+ {static} String RoundTo2Decimals(double)
}
class de.htwg.co2footprint_tracker.helpers.ConnectionHelper {
+ {static} NetworkInfo getNetworkInfo(Context)
+ {static} boolean isConnectedWifi(Context)
+ {static} ConnectionType getNetworkClass(Context)
}
class de.htwg.co2footprint_tracker.helpers.PreferenceManagerHelper {
+ {static} void setStartTime(Context)
+ {static} long getStartTime(Context)
+ {static} void clearStoredStartTime(Context)
+ {static} void setDeviceType(Context)
+ {static} int getDeviceType(Context)
+ {static} void setAdminArea(Context,String)
+ {static} String getAdminArea(Context)
+ {static} void setServiceState(Context,String)
+ {static} String getServiceState(Context)
+ {static} void setTodayTotalToggleState(Context,int)
+ {static} int getTodayTotalToggleState(Context)
}
class de.htwg.co2footprint_tracker.database.DatabaseHelper {
- {static} String TAG
- {static} String DATABASE_FILE_NAME
- {static} String TABLE_NAME_DATA_PER_MINUTE_TABLE
- {static} String TABLE_NAME_DATA_PER_HOUR_TABLE
- {static} String TABLE_NAME_DATA_PER_DAY_TABLE
- {static} String TABLE_NAME_DATA_PER_WEEK_TABLE
- {static} String TABLE_NAME_DATA_PER_MONTH_TABLE
- {static} String NAME
- {static} String TIMESTAMP
- {static} String VERSION
- {static} String PACKAGE_NAME
- {static} String PACKAGE_UID
- {static} String DUPLICATE_UIDS
- {static} String RECEIVED_BYTES_WIFI
- {static} String RECEIVED_BYTES_MOBILE
- {static} String RECEIVED_BYTES_TOTAL
- {static} String TRANSMITTED_BYTES_WIFI
- {static} String TRANSMITTED_BYTES_MOBILE
- {static} String TRANSMITTED_BYTES_TOTAL
- {static} String RECEIVED_PACKETS_WIFI
- {static} String RECEIVED_PACKETS_MOBILE
- {static} String RECEIVED_PACKETS_TOTAL
- {static} String TRANSMITTED_PACKETS_WIFI
- {static} String TRANSMITTED_PACKETS_MOBILE
- {static} String TRANSMITTED_PACKETS_TOTAL
- {static} String ENERGY_CONSUMPTION
- {static} String CONNECTION_TYPE
- {static} String MERGE_KEY
- {static} DatabaseHelper databaseHelperInstance
+ {static} DatabaseHelper getInstance(Context)
+ {static} DatabaseHelper getInstanceObject()
+ void addData(Package)
+ void cumulateDailyData(ContentValues,Package)
- String generateMergeKey(Package)
- void createTables(SQLiteDatabase)
- void createTableFor(String,SQLiteDatabase)
- void dropTables(SQLiteDatabase)
- void dropTable(SQLiteDatabase,String)
+ void clearDb()
+ void purgeDB()
+ Double getTotalEnergyConsumption()
+ Long getTotalReceivedBytes()
+ Double getEnergyConsumptionForToday()
+ Long getTotalBytesForToday()
+ Cursor getData(DatabaseInterval)
+ Cursor getTotalsForPackage(int)
+ double getTotalEnergyConsumptionForPackage(int)
+ long getTotalReceivedBytesForPackage(int)
+ double getTotalEnergyConsumption(HashSet<Integer>)
+ long getTotalReceivedBytes(HashSet<Integer>)
+ List<Consumer> getTopConsumingApps(Context)
+ List<Consumer> getTopConsumingAppsForToday(Context)
+ void clearOldDbEntries()
+ void onCreate(SQLiteDatabase)
+ void onUpgrade(SQLiteDatabase,int,int)
}
class de.htwg.co2footprint_tracker.model.Co2Equivalent {
- String value
- String label
- String description
- String co2
- int image
+ {static} List<Co2Equivalent> getEquivalents(double)
+ String getValue()
+ void setValue(String)
+ String getLabel()
+ void setLabel(String)
+ int getImage()
+ void setImage(int)
- {static} String buildCo2String(double,double)
+ String getDescription()
+ void setDescription(String)
+ String getCo2()
+ void setCo2(String)
}
class de.htwg.co2footprint_tracker.model.InitialBucketContainer {
- {static} String WIFI_PREFIX
- {static} String MOBILE_PREFIX
- {static} String RECEIVED_PREFIX
- {static} String TRANSMITTED_PREFIX
- {static} String DATA_PREFIX
- {static} String PACKET_PREFIX
- {static} boolean newRun
- {static} HashMap<String,Long> mappedPackageData
+ {static} HashMap<String,Long> getOurMap()
+ {static} void putInitialTransmittedWifiData(int,long)
+ {static} long getInitialTransmittedWifiData(int)
+ {static} void putInitialReceivedWifiData(int,long)
+ {static} long getInitialReceivedWifiData(int)
+ {static} void putInitialTransmittedWifiPacket(int,long)
+ {static} long getInitialTransmittedWifiPacket(int)
+ {static} void putInitialReceivedWifiPacket(int,long)
+ {static} long getInitialReceivedWifiPacket(int)
+ {static} void putInitialTransmittedMobileData(int,long)
+ {static} long getInitialTransmittedMobileData(int)
+ {static} void putInitialReceivedMobileData(int,long)
+ {static} long getInitialReceivedMobileData(int)
+ {static} void putInitialTransmittedMobilePacket(int,long)
+ {static} long getInitialTransmittedMobilePacket(int)
+ {static} void putInitialReceivedMobilePacket(int,long)
+ {static} long getInitialReceivedMobilePacket(int)
+ {static} void clearMappedPackageData()
+ {static} boolean isNewRun()
+ {static} void setNewRun(boolean)
}
class de.htwg.co2footprint_tracker.MainActivity {
- {static} WeakReference<MainActivity> weakActivity
- boolean isInForeground
- ActivityMainBinding binding
~ FirebaseRemoteConfig mFirebaseRemoteConfig
+ {static} MainActivity getWeakInstanceActivity()
# void onCreate(Bundle)
# void onStart()
# void onResume()
# void onPause()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void stopTracking()
+ void startTracking()
+ void navigateToFragment(Fragment,boolean)
- void foregroundServiceAction(String)
+ void refreshUi()
}
class de.htwg.co2footprint_tracker.helpers.PackageHelper {
+ {static} HashSet<Integer> getApplicationUids(Context)
+ {static} ArrayList<Package> getPackagesData(Context)
+ {static} int getPackageUid(Context,String)
}
class de.htwg.co2footprint_tracker.model.Consumer {
- Drawable logo
- String name
- double energyConsumption
+ String getName()
+ void setName(String)
+ String getEnergyConsumption()
+ void setEnergyConsumption(double)
+ Drawable getLogo()
+ void setLogo(Drawable)
}
class de.htwg.co2footprint_tracker.helpers.UiHelper {
- {static} UiHelper uiHelper
+ {static} UiHelper getInstance()
+ void changeStartStopButtonAccordingToCurrentState(Button,Activity)
}
class de.htwg.co2footprint_tracker.helpers.KillAppEventHandleReceiver {
+ void onReceive(Context,Intent)
}
class de.htwg.co2footprint_tracker.views.tips.TipsFragment {
- FragmentTipBinding binding
- ExpandableListView expandableListView
- ExpandableListViewAdapter expandableListViewAdapter
- List<String> listDataGroup
- HashMap<String,List<String>> listDataChild
+ {static} TipsFragment getInstance()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onActivityCreated(Bundle)
- void initViews()
- void initListeners()
- void initObjects()
- void initListData()
}
class de.htwg.co2footprint_tracker.services.NetworkStatsExecutorService {
- PowerManager.WakeLock wakeLock
- boolean isServiceStarted
- ArrayList<Package> packageList
- TimerTask timerTask
+ IBinder onBind(Intent)
+ int onStartCommand(Intent,int,int)
+ void onCreate()
+ void onDestroy()
+ void onTaskRemoved(Intent)
- void startService()
- void stopService()
- Notification createNotification()
}
class de.htwg.co2footprint_tracker.helpers.PermissionHelper {
- MainActivity activity
- {static} PermissionHelper permissionHelper
+ void onRequestPermissionsResult(int,String[],int[])
+ {static} PermissionHelper getInstance()
+ void processPermissionHandling()
- boolean hasNetworkHistoryReadingPermission()
- void requestReadNetworkHistoryAccess()
}
class de.htwg.co2footprint_tracker.services.NetworkStatsUpdateService {
- String getSubscriberId(Context,int)
# void onHandleIntent(Intent)
- void saveToDatabase(Context,long,ArrayList<Package>)
- boolean packetHasChanges(Package)
}
class de.htwg.co2footprint_tracker.utils.Constants {
}
interface de.htwg.co2footprint_tracker.utils.Constants.PERMISSION {
~ int RC_LOCATION_READ_PHONE_STATE_ACCESS_NETWORK_STATE
~ int RC_LOCATION
}
interface de.htwg.co2footprint_tracker.utils.Constants.ACTION {
~ String PROCESS_LATEST_NETWORK_TRAFFIC
~ String PACKAGE_LIST_UPDATED
~ String UPDATE_SERVICE_SCHEDULER
~ String RESTART_SCHEDULER_SERVICE
~ String START_SERVICE
~ String STOP_SERVICE
}
interface de.htwg.co2footprint_tracker.utils.Constants.PARAMS {
~ String PACKAGE_LIST
~ String SAVE_STATS_TO_FILE
}
interface de.htwg.co2footprint_tracker.utils.Constants.PERSISTENCY {
~ String PREFERENCE_STARTING_TIME_KEY
~ long NO_START_TIME_SET
~ String DEVICE_IS_TABLET
~ int DEVICE_TYPE_NOT_SET
~ int DEVICE_TYPE_TABLET
~ int DEVICE_TYPE_NOT_TABLET
~ String ADMINISTRATION_AREA
~ String SERVICE_STARTED
~ String SERVICE_STOPPED
~ String TODAY_TOTAL_TOGGLE_STATE
~ int TOGGLE_STATE_NOT_SET
~ int TOGGLE_STATE_TODAY
~ int TOGGLE_STATE_TOTAL
}
interface de.htwg.co2footprint_tracker.utils.Constants.LOG {
~ String TAG
}
interface de.htwg.co2footprint_tracker.utils.Constants.ELECTRICITY {
~ double VORARLBERG_FACTOR
~ double APPENZELL_AUSS_FACTOR
~ double APPENZELL_INN_FACTOR
~ double SCHAFFHAUSEN_FACTOR
~ double ST_GALLEN_FACTOR
~ double THURGAU_FACTOR
~ double ZUERICH_FACTOR
~ double BADEN_WUERTTEMBERG_FACTOR
~ double BAYERN_FACTOR
~ double LICHTENSTEIN_FACTOR
}
class de.htwg.co2footprint_tracker.utils.Co2CalculationUtils {
- {static} double ENERGY_IMPACT_SMARTPHONE
- {static} double AVERAGE_CONSUMPTION_ACCESS_NETWORK_AND_CPE
- {static} double AVERAGE_ENERGY_INTESITY_OF_LONG_HAUL_AND_METRO
- {static} double ELECTRICITY_CONSUMPTION_BY_DATACENTERS
- {static} double KHW_TO_CO2_CONVERSION_VALUE
+ {static} MainCardModel calculateMainCardData(HashSet<Integer>,Context)
- double calculateTotalEnergyConsumption(double,double)
+ double calculateTotalEnergyConsumption(double,long,String)
+ double calculateSmartphoneEnergyConsumption(double)
+ double calculateInternetEnergyConsumption(double)
+ double calculateDataCenterEnergyConsumption(double)
+ double calculateDslamAndCpeEnergyConsumption()
- double bytesToGB(long)
}


androidx.fragment.app.Fragment <|-- de.htwg.co2footprint_tracker.views.data.DataFragment
android.os.Parcelable <|.. de.htwg.co2footprint_tracker.model.Package
de.htwg.co2footprint_tracker.model.Comparable <|.. de.htwg.co2footprint_tracker.model.Package
android.widget.BaseExpandableListAdapter <|-- de.htwg.co2footprint_tracker.views.tips.ExpandableListViewAdapter
de.htwg.co2footprint_tracker.views.data.Adapter <|-- de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter
de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter +.. de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter.ItemClickListener
de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter +.. de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter.ViewHolder
de.htwg.co2footprint_tracker.views.data.OnClickListener <|.. de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter.ViewHolder
de.htwg.co2footprint_tracker.views.data.ViewHolder <|-- de.htwg.co2footprint_tracker.views.data.DataRecyclerViewAdapter.ViewHolder
android.app.Activity <|-- de.htwg.co2footprint_tracker.helpers.LocationHelper
android.database.sqlite.SQLiteOpenHelper <|-- de.htwg.co2footprint_tracker.database.DatabaseHelper
androidx.appcompat.app.AppCompatActivity <|-- de.htwg.co2footprint_tracker.MainActivity
android.content.BroadcastReceiver <|-- de.htwg.co2footprint_tracker.helpers.KillAppEventHandleReceiver
androidx.fragment.app.Fragment <|-- de.htwg.co2footprint_tracker.views.tips.TipsFragment
android.app.Service <|-- de.htwg.co2footprint_tracker.services.NetworkStatsExecutorService
android.app.Activity <|-- de.htwg.co2footprint_tracker.helpers.PermissionHelper
android.app.IntentService <|-- de.htwg.co2footprint_tracker.services.NetworkStatsUpdateService
de.htwg.co2footprint_tracker.utils.Constants +.. de.htwg.co2footprint_tracker.utils.Constants.PERMISSION
de.htwg.co2footprint_tracker.utils.Constants +.. de.htwg.co2footprint_tracker.utils.Constants.ACTION
de.htwg.co2footprint_tracker.utils.Constants +.. de.htwg.co2footprint_tracker.utils.Constants.PARAMS
de.htwg.co2footprint_tracker.utils.Constants +.. de.htwg.co2footprint_tracker.utils.Constants.PERSISTENCY
de.htwg.co2footprint_tracker.utils.Constants +.. de.htwg.co2footprint_tracker.utils.Constants.LOG
de.htwg.co2footprint_tracker.utils.Constants +.. de.htwg.co2footprint_tracker.utils.Constants.ELECTRICITY
@enduml